server:
  port: 8080

logging:
  file:
    name: manageit.log

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5400/manageit
    username: manageit
    password: admin
    driver-class-name: org.postgresql.Driver


vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,com.example.application